(defproject edu.umass/surveyman "1.5"
    :description "SurveyMan is a programming language and runtime system for designing, debugging, and deploying surveys on the web at scale."
    :url "http://surveyman.org"
    :repositories [["java.net" "http://download.java.net/maven/2"]]
    :dependencies [[org.clojure/clojure "1.6.0"]
                   [re-rand "0.1.0"]
                   [com.github.fge/json-schema-validator "2.0.1"]
                   [incanter "1.5.4"]
                   [clj-webdriver "0.6.0"]
                   [org.clojure/data.csv "0.1.2"]
                   [org.seleniumhq.selenium/selenium-java "2.41.0"]
                   [org.clojure/math.numeric-tower "0.0.4"]
                   [com.googlecode.htmlcompressor/htmlcompressor "1.4"]
                   [com.google.javascript/closure-compiler "v20130823"]
                   [org.jsoup/jsoup "1.7.3"]
                   [ring "1.3.0"]
                   [com.googlecode.json-simple/json-simple "1.1"]
                   [log4j/log4j "1.2.12"]
                   [dom4j/dom4j "1.6.1"]
                   [com.google.code.gson/gson "2.2.4"]
                   [net.sf.supercsv/super-csv "2.1.0"]
                   [org.clojars.zaxtax/java-aws-mturk "1.6.2"]
                   [aws-java-sdk "1.3.1"]
                   [org.eclipse.jetty/jetty-server "7.6.8.v20121106"]
                   [org.apache.commons/commons-math3 "3.0"]
                   [org.clojure/data.json "0.2.4"]
                   [net.sourceforge.argparse4j/argparse4j "0.2.0"]
                 ]
    :resource-paths ["src/main/resources" "src/javascript"]
    :main system.Runner
    :java-source-paths ["src/main/java" "src/test/java"]
    :source-paths ["src/main/clojure" "src/test/clojure"]
    :aot [qc.metrics report system.mturk.response-converter debug-server]
    :plugins [[lein-junit "1.1.2"]
              [lein-localrepo "0.5.3"]]
    :test-paths ["src/test/clojure"]
    :junit ["src/test/java"]
    :jvm-opts ["-ea"]
    :omit-source true
  )
