{ "filename" : "data/tests/test3.csv"
, "breakoff" :  "true"
, "survey" : [ { "id" : "1"
                , "questions" : [ { "id" : "q_2_2"
                                    , "qtext" : "How likely are you to enjoy sitting next to a baby on a plane?"
                                    , "options" : [ { "id" : "comp_2_3", "otext" : "Not Likely" }
                                                    , { "id" : "comp_3_3", "otext" : "Less Likely" }
                                                    , { "id" : "comp_4_3", "otext" : "Somewhat Likely" }
                                                    , { "id" : "comp_5_3", "otext" : "Very Likely" }
                                                    , { "id" : "comp_6_3", "otext" : "Most Certainly" } ]
                                    , "ordered" : "true"}
                                  , { "id" : "q_7_2"
                                    , "qtext" : "<p>How confident are you that the sound you're about to hear is from a crying baby?<p><audio controls preload=none><source src=https://dl.dropboxusercontent.com/u/44930665/survey_resources/waaahhh.wav type=audio/wav></source></audio>"
                                    , "options" : [ { "id" : "comp_7_3", "otext" : " Least Confident " }
                                                    , { "id" : "comp_8_3", "otext" : " Less Confident" }, { "id" : "comp_9_3", "otext" : " More Confident" }, { "id" : "comp_10_3", "otext" : " Most Confident" } ], "ordered" : "true"}, { "id" : "q_11_2", "qtext" : "<p>Would you describe the following image as "cute"?</p><img src=https://dl.dropboxusercontent.com/u/44930665/survey_resources/cherubic_child.jpeg></img></p>" , "options" : [ { "id" : "comp_11_3", "otext" : "Yes" }, { "id" : "comp_12_3", "otext" : "No" }, { "id" : "comp_13_3", "otext" : "I don't understand the question" } ]} ]  }, { "id" : "2", "questions" : [ { "id" : "q_14_2", "qtext" : "How likely are you to enjoy sitting through Snakes on a Plane? Check all that apply." , "options" : [ { "id" : "comp_14_3", "otext" : "I'd rather sit on a snake on a plane" }, { "id" : "comp_15_3", "otext" : "I lurve me some Samuel L. Jackson" }, { "id" : "comp_16_3", "otext" : "It depends on my level of intoxication" }, { "id" : "comp_17_3", "otext" : "I've sat through worse" } ], "exclusive" : "false"}, { "id" : "q_18_2", "qtext" : "What is your age?" , "options" : [ { "id" : "comp_18_3", "otext" : "<18" }, { "id" : "comp_19_3", "otext" : "18-25" }, { "id" : "comp_20_3", "otext" : "26-35" }, { "id" : "comp_21_3", "otext" : "36-45" }, { "id" : "comp_22_3", "otext" : "46-65" }, { "id" : "comp_23_3", "otext" : "66+" } ], "randomize" : "false", "ordered" : "true"}, { "id" : "q_24_2", "qtext" : "What is your year of birth?" , "options" : [ { "id" : "comp_24_3", "otext" : "1995" }, { "id" : "comp_25_3", "otext" : "1994" }, { "id" : "comp_26_3", "otext" : "1993" }, { "id" : "comp_27_3", "otext" : "1992" }, { "id" : "comp_28_3", "otext" : "1981" }, { "id" : "comp_29_3", "otext" : "1980" }, { "id" : "comp_30_3", "otext" : "1979" } ], "randomize" : "false", "ordered" : "true"} ]  }, { "id" : "3", "questions" : [ { "id" : "q_31_2", "qtext" : "Have you ever sat next to a baby on a plane while watching Snakes on a Plane?" , "options" : [ { "id" : "comp_31_3", "otext" : "true" }, { "id" : "comp_32_3", "otext" : "false" } ]}, { "id" : "q_33_2", "qtext" : "How desperately bored would you have to be to watch a film about baby snakes on a Plane?" , "options" : [ { "id" : "comp_33_3", "otext" : "Very Bored" }, { "id" : "comp_34_3", "otext" : "Mildly Bored" }, { "id" : "comp_35_3", "otext" : "Zoned Out" }, { "id" : "comp_36_3", "otext" : "Interested" }, { "id" : "comp_37_3", "otext" : "Fascinated" } ], "ordered" : "true"} ]  } ] };